### ISSUE TITLE
Potential Large Object Heap fragmentation after repeated resizing

### ISSUE THREAD

**Issue by stakx** [imazen/lightresize#6]
I might be mistaken about it, but will mention this in case that I'm not: :)

As far as I can see, LightResize currently makes no provisions against [Large Object Heap (LOH) fragmentation](https://www.simple-talk.com/dotnet/.net-framework/the-dangers-of-the-large-object-heap/). This means that repeated use of this library in the same process (or `AppDomain`?) could eventually lead to an `OutOfMemoryException`.

Take for example the way how a resized image is first buffered to a (seekable) `MemoryStream` before being written to disk as a PNG. `MemoryStream`s are backed by `byte[]` buffers, which, in the case of image data, can easily become larger than the LOH threshold of approx. 85,000 bytes.

Some options for dealing with this potential problem:
- Pool the `byte[]` buffers, i.e. reuse them in order to reduce new LOH allocations. Pooling might work more efficiently if the pooled buffers are all of the same size, or a multiple of some value.
- Since the needed buffers have a short life span, and are therefore unlikely to live through a garbage collection, one could, instead of letting `MemoryStream` allocate a large `byte[]` buffer on the LOH, allocate several small `byte[]` buffers and chain them together. One would have to hide this behind a custom implementation of `Stream`. The advantage being that these individual small buffers stay in GC gen 0 (or if we're unlucky, in gen 1) where GC performs memory compaction.
- Instead of doing the above yourself, use the recently-published [`Microsoft.IO.RecycableMemoryStream`](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream). (See also [this blog post by Ben Watson](http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/), for more details about it.) This would however mean that LightResize can no longer target .NET 2.
- Or, as a completely different approach, avoid LOH fragmentation by using unmanaged memory (which isn't dealt with by GC at all), i.e. use something akin to `UnmanagedMemoryStream`. I suspect that GDI+ and therefore `System.Drawing.Bitmap` use unmanaged memory, so this shouldn't be altogether unreasonable.

Btw. your excellent 2009 article ["20 image resizing pitfalls"](http://www.nathanaeljones.com/blog/2009/20-image-resizing-pitfalls) also makes no mention of LOH fragmentation (see points 1 and 6).

**Comment by stakx** [comment]
Closing this issue as I suspect that you might have gone on to work on other projects.

**Comment by lilith** [comment]
I haven't ever observed an OutOfMemory exception coming from a MemoryStream allocation. The current LOH allocator is slightly less bad today; it at least will reuse older gaps. 

Fragmented memory is actually a big problem when decompressing, as that requires two orders of magnitude more space than the compressed stream. By design (and unlike MemoryStream), bitmap data is not permitted to be paged to disk (you can mimic this by using [VirtualLock with the right flags](https://blogs.msdn.microsoft.com/oldnewthing/20140207-00/?p=1833/)). 

OOM appears to primarily occur during `new Bitmap()`, and nearly always when when running in a 31-bit address space. It's more common when there are other processes fragmenting memory, or when the 27-hour recycle period is turned off for an app.

**Comment by stakx** [comment]
That is good to know. If you haven't seen the need to replace MemoryStream / avoid LOH problems in ImageResizer, then I don't see any immediate reason to worry further about this in the context of LightResize.

Thank you for giving some good information above; I might investigate this topic further at a later time, just out of curiosity.
